package com.fxq.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

import com.fxq.annotation.*;

public final class RandomMessage {
  private RandomMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MarketDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MarketData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double Ask1 = 1;</code>
     * @return Whether the ask1 field is set.
     */
    boolean hasAsk1();
    /**
     * <code>optional double Ask1 = 1;</code>
     * @return The ask1.
     */
    double getAsk1();

    /**
     * <code>optional int32 AskLot1 = 2;</code>
     * @return Whether the askLot1 field is set.
     */
    boolean hasAskLot1();
    /**
     * <code>optional int32 AskLot1 = 2;</code>
     * @return The askLot1.
     */
    int getAskLot1();

    /**
     * <code>optional string AskChannel1 = 3;</code>
     * @return Whether the askChannel1 field is set.
     */
    boolean hasAskChannel1();
    /**
     * <code>optional string AskChannel1 = 3;</code>
     * @return The askChannel1.
     */
    String getAskChannel1();
    /**
     * <code>optional string AskChannel1 = 3;</code>
     * @return The bytes for askChannel1.
     */
    com.google.protobuf.ByteString
        getAskChannel1Bytes();

    /**
     * <code>optional double Bid1 = 4;</code>
     * @return Whether the bid1 field is set.
     */
    boolean hasBid1();
    /**
     * <code>optional double Bid1 = 4;</code>
     * @return The bid1.
     */
    double getBid1();

    /**
     * <code>optional int32 BidLot1 = 5;</code>
     * @return Whether the bidLot1 field is set.
     */
    boolean hasBidLot1();
    /**
     * <code>optional int32 BidLot1 = 5;</code>
     * @return The bidLot1.
     */
    int getBidLot1();

    /**
     * <code>optional string BidChannel1 = 6;</code>
     * @return Whether the bidChannel1 field is set.
     */
    boolean hasBidChannel1();
    /**
     * <code>optional string BidChannel1 = 6;</code>
     * @return The bidChannel1.
     */
    String getBidChannel1();
    /**
     * <code>optional string BidChannel1 = 6;</code>
     * @return The bytes for bidChannel1.
     */
    com.google.protobuf.ByteString
        getBidChannel1Bytes();
  }
  /**
   * Protobuf type {@code MarketData}
   */
  @GetDoubleMethod({"Ask1","Bid1"})
  @GetStringMethod({"AskChannel1","BidChannel1"})
  @GetIntMethod({"AskLot1","BidLot1"})
  @IsNullMethod({"Ask1","Bid1","AskChannel1","BidChannel1","AskLot1","BidLot1"})
  public static final class MarketData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MarketData)
      MarketDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MarketData.newBuilder() to construct.
    private MarketData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MarketData() {
      askChannel1_ = "";
      bidChannel1_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MarketData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RandomMessage.internal_static_MarketData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RandomMessage.internal_static_MarketData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MarketData.class, Builder.class);
    }

    private int bitField0_;
    public static final int ASK1_FIELD_NUMBER = 1;
    private double ask1_ = 0D;
    /**
     * <code>optional double Ask1 = 1;</code>
     * @return Whether the ask1 field is set.
     */
    @Override
    public boolean hasAsk1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional double Ask1 = 1;</code>
     * @return The ask1.
     */
    @Override
    public double getAsk1() {
      return ask1_;
    }

    public static final int ASKLOT1_FIELD_NUMBER = 2;
    private int askLot1_ = 0;
    /**
     * <code>optional int32 AskLot1 = 2;</code>
     * @return Whether the askLot1 field is set.
     */
    @Override
    public boolean hasAskLot1() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 AskLot1 = 2;</code>
     * @return The askLot1.
     */
    @Override
    public int getAskLot1() {
      return askLot1_;
    }

    public static final int ASKCHANNEL1_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object askChannel1_ = "";
    /**
     * <code>optional string AskChannel1 = 3;</code>
     * @return Whether the askChannel1 field is set.
     */
    @Override
    public boolean hasAskChannel1() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string AskChannel1 = 3;</code>
     * @return The askChannel1.
     */
    @Override
    public String getAskChannel1() {
      Object ref = askChannel1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        askChannel1_ = s;
        return s;
      }
    }
    /**
     * <code>optional string AskChannel1 = 3;</code>
     * @return The bytes for askChannel1.
     */
    @Override
    public com.google.protobuf.ByteString
        getAskChannel1Bytes() {
      Object ref = askChannel1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        askChannel1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BID1_FIELD_NUMBER = 4;
    private double bid1_ = 0D;
    /**
     * <code>optional double Bid1 = 4;</code>
     * @return Whether the bid1 field is set.
     */
    @Override
    public boolean hasBid1() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional double Bid1 = 4;</code>
     * @return The bid1.
     */
    @Override
    public double getBid1() {
      return bid1_;
    }

    public static final int BIDLOT1_FIELD_NUMBER = 5;
    private int bidLot1_ = 0;
    /**
     * <code>optional int32 BidLot1 = 5;</code>
     * @return Whether the bidLot1 field is set.
     */
    @Override
    public boolean hasBidLot1() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 BidLot1 = 5;</code>
     * @return The bidLot1.
     */
    @Override
    public int getBidLot1() {
      return bidLot1_;
    }

    public static final int BIDCHANNEL1_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile Object bidChannel1_ = "";
    /**
     * <code>optional string BidChannel1 = 6;</code>
     * @return Whether the bidChannel1 field is set.
     */
    @Override
    public boolean hasBidChannel1() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string BidChannel1 = 6;</code>
     * @return The bidChannel1.
     */
    @Override
    public String getBidChannel1() {
      Object ref = bidChannel1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bidChannel1_ = s;
        return s;
      }
    }
    /**
     * <code>optional string BidChannel1 = 6;</code>
     * @return The bytes for bidChannel1.
     */
    @Override
    public com.google.protobuf.ByteString
        getBidChannel1Bytes() {
      Object ref = bidChannel1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bidChannel1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(1, ask1_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, askLot1_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, askChannel1_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(4, bid1_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, bidLot1_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, bidChannel1_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, ask1_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, askLot1_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, askChannel1_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, bid1_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, bidLot1_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, bidChannel1_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MarketData)) {
        return super.equals(obj);
      }
      MarketData other = (MarketData) obj;

      if (hasAsk1() != other.hasAsk1()) return false;
      if (hasAsk1()) {
        if (Double.doubleToLongBits(getAsk1())
            != Double.doubleToLongBits(
                other.getAsk1())) return false;
      }
      if (hasAskLot1() != other.hasAskLot1()) return false;
      if (hasAskLot1()) {
        if (getAskLot1()
            != other.getAskLot1()) return false;
      }
      if (hasAskChannel1() != other.hasAskChannel1()) return false;
      if (hasAskChannel1()) {
        if (!getAskChannel1()
            .equals(other.getAskChannel1())) return false;
      }
      if (hasBid1() != other.hasBid1()) return false;
      if (hasBid1()) {
        if (Double.doubleToLongBits(getBid1())
            != Double.doubleToLongBits(
                other.getBid1())) return false;
      }
      if (hasBidLot1() != other.hasBidLot1()) return false;
      if (hasBidLot1()) {
        if (getBidLot1()
            != other.getBidLot1()) return false;
      }
      if (hasBidChannel1() != other.hasBidChannel1()) return false;
      if (hasBidChannel1()) {
        if (!getBidChannel1()
            .equals(other.getBidChannel1())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAsk1()) {
        hash = (37 * hash) + ASK1_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getAsk1()));
      }
      if (hasAskLot1()) {
        hash = (37 * hash) + ASKLOT1_FIELD_NUMBER;
        hash = (53 * hash) + getAskLot1();
      }
      if (hasAskChannel1()) {
        hash = (37 * hash) + ASKCHANNEL1_FIELD_NUMBER;
        hash = (53 * hash) + getAskChannel1().hashCode();
      }
      if (hasBid1()) {
        hash = (37 * hash) + BID1_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getBid1()));
      }
      if (hasBidLot1()) {
        hash = (37 * hash) + BIDLOT1_FIELD_NUMBER;
        hash = (53 * hash) + getBidLot1();
      }
      if (hasBidChannel1()) {
        hash = (37 * hash) + BIDCHANNEL1_FIELD_NUMBER;
        hash = (53 * hash) + getBidChannel1().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MarketData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MarketData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MarketData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MarketData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MarketData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MarketData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MarketData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MarketData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MarketData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MarketData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MarketData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MarketData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MarketData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MarketData}
     */
    @PutStringMethod({"AskChannel1","BidChannel1"})
    @PutIntMethod({"AskLot1","BidLot1"})
    @PutDoubleMethod({"Ask1","Bid1"})
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MarketData)
        MarketDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RandomMessage.internal_static_MarketData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RandomMessage.internal_static_MarketData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MarketData.class, Builder.class);
      }

      // Construct using RandomMessage.MarketData.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ask1_ = 0D;
        askLot1_ = 0;
        askChannel1_ = "";
        bid1_ = 0D;
        bidLot1_ = 0;
        bidChannel1_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RandomMessage.internal_static_MarketData_descriptor;
      }

      @Override
      public MarketData getDefaultInstanceForType() {
        return MarketData.getDefaultInstance();
      }

      @Override
      public MarketData build() {
        MarketData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MarketData buildPartial() {
        MarketData result = new MarketData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MarketData result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ask1_ = ask1_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.askLot1_ = askLot1_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.askChannel1_ = askChannel1_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.bid1_ = bid1_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.bidLot1_ = bidLot1_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.bidChannel1_ = bidChannel1_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MarketData) {
          return mergeFrom((MarketData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MarketData other) {
        if (other == MarketData.getDefaultInstance()) return this;
        if (other.hasAsk1()) {
          setAsk1(other.getAsk1());
        }
        if (other.hasAskLot1()) {
          setAskLot1(other.getAskLot1());
        }
        if (other.hasAskChannel1()) {
          askChannel1_ = other.askChannel1_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasBid1()) {
          setBid1(other.getBid1());
        }
        if (other.hasBidLot1()) {
          setBidLot1(other.getBidLot1());
        }
        if (other.hasBidChannel1()) {
          bidChannel1_ = other.bidChannel1_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                ask1_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 16: {
                askLot1_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                askChannel1_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 33: {
                bid1_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 40: {
                bidLot1_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                bidChannel1_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double ask1_ ;
      /**
       * <code>optional double Ask1 = 1;</code>
       * @return Whether the ask1 field is set.
       */
      @Override
      public boolean hasAsk1() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional double Ask1 = 1;</code>
       * @return The ask1.
       */
      @Override
      public double getAsk1() {
        return ask1_;
      }
      /**
       * <code>optional double Ask1 = 1;</code>
       * @param value The ask1 to set.
       * @return This builder for chaining.
       */
      public Builder setAsk1(double value) {

        ask1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional double Ask1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAsk1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ask1_ = 0D;
        onChanged();
        return this;
      }

      private int askLot1_ ;
      /**
       * <code>optional int32 AskLot1 = 2;</code>
       * @return Whether the askLot1 field is set.
       */
      @Override
      public boolean hasAskLot1() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 AskLot1 = 2;</code>
       * @return The askLot1.
       */
      @Override
      public int getAskLot1() {
        return askLot1_;
      }
      /**
       * <code>optional int32 AskLot1 = 2;</code>
       * @param value The askLot1 to set.
       * @return This builder for chaining.
       */
      public Builder setAskLot1(int value) {

        askLot1_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 AskLot1 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAskLot1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        askLot1_ = 0;
        onChanged();
        return this;
      }

      private Object askChannel1_ = "";
      /**
       * <code>optional string AskChannel1 = 3;</code>
       * @return Whether the askChannel1 field is set.
       */
      public boolean hasAskChannel1() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string AskChannel1 = 3;</code>
       * @return The askChannel1.
       */
      public String getAskChannel1() {
        Object ref = askChannel1_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          askChannel1_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string AskChannel1 = 3;</code>
       * @return The bytes for askChannel1.
       */
      public com.google.protobuf.ByteString
          getAskChannel1Bytes() {
        Object ref = askChannel1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          askChannel1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string AskChannel1 = 3;</code>
       * @param value The askChannel1 to set.
       * @return This builder for chaining.
       */
      public Builder setAskChannel1(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        askChannel1_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string AskChannel1 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAskChannel1() {
        askChannel1_ = getDefaultInstance().getAskChannel1();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string AskChannel1 = 3;</code>
       * @param value The bytes for askChannel1 to set.
       * @return This builder for chaining.
       */
      public Builder setAskChannel1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        askChannel1_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private double bid1_ ;
      /**
       * <code>optional double Bid1 = 4;</code>
       * @return Whether the bid1 field is set.
       */
      @Override
      public boolean hasBid1() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional double Bid1 = 4;</code>
       * @return The bid1.
       */
      @Override
      public double getBid1() {
        return bid1_;
      }
      /**
       * <code>optional double Bid1 = 4;</code>
       * @param value The bid1 to set.
       * @return This builder for chaining.
       */
      public Builder setBid1(double value) {

        bid1_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional double Bid1 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBid1() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bid1_ = 0D;
        onChanged();
        return this;
      }

      private int bidLot1_ ;
      /**
       * <code>optional int32 BidLot1 = 5;</code>
       * @return Whether the bidLot1 field is set.
       */
      @Override
      public boolean hasBidLot1() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 BidLot1 = 5;</code>
       * @return The bidLot1.
       */
      @Override
      public int getBidLot1() {
        return bidLot1_;
      }
      /**
       * <code>optional int32 BidLot1 = 5;</code>
       * @param value The bidLot1 to set.
       * @return This builder for chaining.
       */
      public Builder setBidLot1(int value) {

        bidLot1_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 BidLot1 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBidLot1() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bidLot1_ = 0;
        onChanged();
        return this;
      }

      private Object bidChannel1_ = "";
      /**
       * <code>optional string BidChannel1 = 6;</code>
       * @return Whether the bidChannel1 field is set.
       */
      public boolean hasBidChannel1() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string BidChannel1 = 6;</code>
       * @return The bidChannel1.
       */
      public String getBidChannel1() {
        Object ref = bidChannel1_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bidChannel1_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string BidChannel1 = 6;</code>
       * @return The bytes for bidChannel1.
       */
      public com.google.protobuf.ByteString
          getBidChannel1Bytes() {
        Object ref = bidChannel1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bidChannel1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string BidChannel1 = 6;</code>
       * @param value The bidChannel1 to set.
       * @return This builder for chaining.
       */
      public Builder setBidChannel1(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        bidChannel1_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional string BidChannel1 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBidChannel1() {
        bidChannel1_ = getDefaultInstance().getBidChannel1();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>optional string BidChannel1 = 6;</code>
       * @param value The bytes for bidChannel1 to set.
       * @return This builder for chaining.
       */
      public Builder setBidChannel1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bidChannel1_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MarketData)
    }

    // @@protoc_insertion_point(class_scope:MarketData)
    private static final MarketData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MarketData();
    }

    public static MarketData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarketData>
        PARSER = new com.google.protobuf.AbstractParser<MarketData>() {
      @Override
      public MarketData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MarketData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MarketData> getParserForType() {
      return PARSER;
    }

    @Override
    public MarketData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string TransType = 1;</code>
     * @return Whether the transType field is set.
     */
    boolean hasTransType();
    /**
     * <code>optional string TransType = 1;</code>
     * @return The transType.
     */
    String getTransType();
    /**
     * <code>optional string TransType = 1;</code>
     * @return The bytes for transType.
     */
    com.google.protobuf.ByteString
        getTransTypeBytes();

    /**
     * <code>optional .MarketData MarketData = 2;</code>
     * @return Whether the marketData field is set.
     */
    boolean hasMarketData();
    /**
     * <code>optional .MarketData MarketData = 2;</code>
     * @return The marketData.
     */
    MarketData getMarketData();
    /**
     * <code>optional .MarketData MarketData = 2;</code>
     */
    MarketDataOrBuilder getMarketDataOrBuilder();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      transType_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RandomMessage.internal_static_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RandomMessage.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    private int bitField0_;
    public static final int TRANSTYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object transType_ = "";
    /**
     * <code>optional string TransType = 1;</code>
     * @return Whether the transType field is set.
     */
    @Override
    public boolean hasTransType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string TransType = 1;</code>
     * @return The transType.
     */
    @Override
    public String getTransType() {
      Object ref = transType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string TransType = 1;</code>
     * @return The bytes for transType.
     */
    @Override
    public com.google.protobuf.ByteString
        getTransTypeBytes() {
      Object ref = transType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        transType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MARKETDATA_FIELD_NUMBER = 2;
    private MarketData marketData_;
    /**
     * <code>optional .MarketData MarketData = 2;</code>
     * @return Whether the marketData field is set.
     */
    @Override
    public boolean hasMarketData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .MarketData MarketData = 2;</code>
     * @return The marketData.
     */
    @Override
    public MarketData getMarketData() {
      return marketData_ == null ? MarketData.getDefaultInstance() : marketData_;
    }
    /**
     * <code>optional .MarketData MarketData = 2;</code>
     */
    @Override
    public MarketDataOrBuilder getMarketDataOrBuilder() {
      return marketData_ == null ? MarketData.getDefaultInstance() : marketData_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getMarketData());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMarketData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      if (hasTransType() != other.hasTransType()) return false;
      if (hasTransType()) {
        if (!getTransType()
            .equals(other.getTransType())) return false;
      }
      if (hasMarketData() != other.hasMarketData()) return false;
      if (hasMarketData()) {
        if (!getMarketData()
            .equals(other.getMarketData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTransType()) {
        hash = (37 * hash) + TRANSTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTransType().hashCode();
      }
      if (hasMarketData()) {
        hash = (37 * hash) + MARKETDATA_FIELD_NUMBER;
        hash = (53 * hash) + getMarketData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RandomMessage.internal_static_Message_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RandomMessage.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using RandomMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMarketDataFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        transType_ = "";
        marketData_ = null;
        if (marketDataBuilder_ != null) {
          marketDataBuilder_.dispose();
          marketDataBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RandomMessage.internal_static_Message_descriptor;
      }

      @Override
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      @Override
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Message buildPartial() {
        Message result = new Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Message result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.transType_ = transType_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.marketData_ = marketDataBuilder_ == null
              ? marketData_
              : marketDataBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.hasTransType()) {
          transType_ = other.transType_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasMarketData()) {
          mergeMarketData(other.getMarketData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                transType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getMarketDataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object transType_ = "";
      /**
       * <code>optional string TransType = 1;</code>
       * @return Whether the transType field is set.
       */
      public boolean hasTransType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string TransType = 1;</code>
       * @return The transType.
       */
      public String getTransType() {
        Object ref = transType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          transType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string TransType = 1;</code>
       * @return The bytes for transType.
       */
      public com.google.protobuf.ByteString
          getTransTypeBytes() {
        Object ref = transType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          transType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string TransType = 1;</code>
       * @param value The transType to set.
       * @return This builder for chaining.
       */
      public Builder setTransType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        transType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string TransType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransType() {
        transType_ = getDefaultInstance().getTransType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string TransType = 1;</code>
       * @param value The bytes for transType to set.
       * @return This builder for chaining.
       */
      public Builder setTransTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        transType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private MarketData marketData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          MarketData, MarketData.Builder, MarketDataOrBuilder> marketDataBuilder_;
      /**
       * <code>optional .MarketData MarketData = 2;</code>
       * @return Whether the marketData field is set.
       */
      public boolean hasMarketData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .MarketData MarketData = 2;</code>
       * @return The marketData.
       */
      public MarketData getMarketData() {
        if (marketDataBuilder_ == null) {
          return marketData_ == null ? MarketData.getDefaultInstance() : marketData_;
        } else {
          return marketDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .MarketData MarketData = 2;</code>
       */
      public Builder setMarketData(MarketData value) {
        if (marketDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          marketData_ = value;
        } else {
          marketDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MarketData MarketData = 2;</code>
       */
      public Builder setMarketData(
          MarketData.Builder builderForValue) {
        if (marketDataBuilder_ == null) {
          marketData_ = builderForValue.build();
        } else {
          marketDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MarketData MarketData = 2;</code>
       */
      public Builder mergeMarketData(MarketData value) {
        if (marketDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            marketData_ != null &&
            marketData_ != MarketData.getDefaultInstance()) {
            getMarketDataBuilder().mergeFrom(value);
          } else {
            marketData_ = value;
          }
        } else {
          marketDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MarketData MarketData = 2;</code>
       */
      public Builder clearMarketData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        marketData_ = null;
        if (marketDataBuilder_ != null) {
          marketDataBuilder_.dispose();
          marketDataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .MarketData MarketData = 2;</code>
       */
      public MarketData.Builder getMarketDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMarketDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .MarketData MarketData = 2;</code>
       */
      public MarketDataOrBuilder getMarketDataOrBuilder() {
        if (marketDataBuilder_ != null) {
          return marketDataBuilder_.getMessageOrBuilder();
        } else {
          return marketData_ == null ?
              MarketData.getDefaultInstance() : marketData_;
        }
      }
      /**
       * <code>optional .MarketData MarketData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MarketData, MarketData.Builder, MarketDataOrBuilder>
          getMarketDataFieldBuilder() {
        if (marketDataBuilder_ == null) {
          marketDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MarketData, MarketData.Builder, MarketDataOrBuilder>(
                  getMarketData(),
                  getParentForChildren(),
                  isClean());
          marketData_ = null;
        }
        return marketDataBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MarketData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MarketData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rmessage.proto\"\334\001\n\nMarketData\022\021\n\004Ask1\030\001" +
      " \001(\001H\000\210\001\001\022\024\n\007AskLot1\030\002 \001(\005H\001\210\001\001\022\030\n\013AskCh" +
      "annel1\030\003 \001(\tH\002\210\001\001\022\021\n\004Bid1\030\004 \001(\001H\003\210\001\001\022\024\n\007" +
      "BidLot1\030\005 \001(\005H\004\210\001\001\022\030\n\013BidChannel1\030\006 \001(\tH" +
      "\005\210\001\001B\007\n\005_Ask1B\n\n\010_AskLot1B\016\n\014_AskChannel" +
      "1B\007\n\005_Bid1B\n\n\010_BidLot1B\016\n\014_BidChannel1\"d" +
      "\n\007Message\022\026\n\tTransType\030\001 \001(\tH\000\210\001\001\022$\n\nMar" +
      "ketData\030\002 \001(\0132\013.MarketDataH\001\210\001\001B\014\n\n_Tran" +
      "sTypeB\r\n\013_MarketDataB\017B\rRandomMessageb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MarketData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MarketData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MarketData_descriptor,
        new String[] { "Ask1", "AskLot1", "AskChannel1", "Bid1", "BidLot1", "BidChannel1", "Ask1", "AskLot1", "AskChannel1", "Bid1", "BidLot1", "BidChannel1", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new String[] { "TransType", "MarketData", "TransType", "MarketData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
